name: ACCURATE 2A Evaluation Board
description: README.md
website: https://github.com/boukabache/ACCURATE2_EvalBoard
licenses:
  - CERN-OHL-P-2.0
  - GPL-3.0-or-later
version: 1.0.0
universities:
  - CERN
images:
  - https://github.com/boukabache/ACCURATE2_EvalBoard/raw/master/manufacturing_outputs/assets/EvalBoard.png
documentation: https://github.com/boukabache/ACCURATE2_EvalBoard/wiki
tags:
  - 'ASIC'
  - 'FPGA'
  - 'Measurements'
  - 'CERN'
