const __FlashStringHelper* scpiCommandTree = F(
    "Command tree with only SCPI Required Commands and IEEE Mandated Commands:\n"
    "STATus\n"
    "    :OPERation\n"
    "        :CONDition?\n"
    "        :ENABle\n"
    "        [:EVENt]?\n"
    "    :QUEStionable\n"
    "        :CONDition?\n"
    "        :ENABle\n"
    "        [:EVENt]?\n"
    "    :PRESet\n"
    "SYSTem\n"
    "    :ERRor\n"
    "        [:NEXT]?\n"
    "    :VERSion?\n"
    "*CLS\n"
    "*ESE\n"
    "*ESE?\n"
    "*ESR?\n"
    "*IDN?\n"
    "*OPC\n"
    "*OPC?\n"
    "*RST\n"
    "*SRE\n"
    "*SRE?\n"
    "*STB\n"
    "*TST?\n"
    "*WAI\n"
    "\n"
    "Custom commands to operate the Evaluation Board:\n"
    "CONFigure\n"
    "    :DAC\n"
    "        :VOLTage <port>A|B|C|D|E|F|G|H ,<voltage>\n"
    "        :VOLTage? <port> A|B|C|D|E|F|G|H\n"
    "    :ACCUrate\n"
    "        :CHARGE\n"
    "        :CHARGE?\n"
    "        :COOLdown\n"
    "        :COOLdown?\n"
    "        :RESET\n"
    "        :RESET?\n"
    "        :TCHARGE\n"
    "        :TCHARGE?\n"
    "        :TINJection\n"
    "        :TINJection?\n"
    "        :DISABLE\n"
    "        :DISABLE?\n"
    "        :SINGLY\n"
    "        :SINGLY?\n"
    "    :SERIal\n"
    "        :STREAM\n"
    "        :STREAM?\n"
    "        :RAW\n"
    "        :RAW?\n"
);