/**
 * @file scpiInterfaceCommandTree.h
 * @brief SCPI Command Tree for the Evaluation Board
 * 
 * This file contains the command tree string for the SCPI interface.
 * It is used to print the command tree when the user requests help.
 * The string is saved in flash memory and not in RAM for optimisation purposes.
*/


const __FlashStringHelper* scpiCommandTree = F(
    "SCPI Required Commands and IEEE Mandated Commands:\n"
    "WARNING: NOT ALL THE LISTED COMMANDS ARE IMPLEMENTED YET\n"
    "STATus\n"
    "    :OPERation\n"
    "        :CONDition?\n"
    "        :ENABle\n"
    "        [:EVENt]?\n"
    "    :QUEStionable\n"
    "        :CONDition?\n"
    "        :ENABle\n"
    "        [:EVENt]?\n"
    "    :PRESet\n"
    "SYSTem\n"
    "    :ERRor\n"
    "        [:NEXT]?\n"
    "    :VERSion?\n"
    "*CLS\n"
    "*ESE\n"
    "*ESE?\n"
    "*ESR?\n"
    "*IDN?\n"
    "*OPC\n"
    "*OPC?\n"
    "*RST\n"
    "*SRE\n"
    "*SRE?\n"
    "*STB\n"
    "*TST?\n"
    "*WAI\n"
    "------------------------------------------------\n"
    "Custom commands to operate the Evaluation Board:\n"
    "CONFigure\n"
    "    :DAC\n"
    "        :VOLTage A|B|C|D|E|F|G|H ,<voltage(V)>\n"
    "        :VOLTage? A|B|C|D|E|F|G|H\n"
    "    :ACCUrate\n"
    "        :CHARGE 1|2|3 ,<chargeQuanta(LSB)>\n"
    "        :CHARGE? 1|2|3\n"
    "        :COOLdown MIN|MAX ,1|2|3 ,<time(clk)>\n"
    "        :COOLdown? MIN|MAX ,1|2|3\n"
    "        :RESET 1|0\n"
    "        :RESET?\n"
    "        :TCHARGE <time(clk)>\n"
    "        :TCHARGE?\n"
    "        :TINJection <time(clk)>\n"
    "        :TINJection?\n"
    "        :DISABLE 1|2|3 ,1|0\n"
    "        :DISABLE? 1|2|3\n"
    "        :SINGLY 1|0\n"
    "        :SINGLY?\n"
    "    :SERIal\n"
    "        :STREAM ON|OFF\n"
    "        :STREAM?\n"
    "        :RAW ON|OFF\n"
    "        :RAW?\n"
    "        :LOG ON|OFF\n"
    "        :LOG?\n"
);